baseurl = "https://npmrunpodcast.com/"
languageCode = "en-us"
title = "npm run podcast"
theme = "super"
googleAnalytics = "UA-2011466-11"
disqusShortname = "zeroasterisk"
# themesdir = "../.."


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "books"
    parent = "resources"
[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "books"
    parent = "resources"

[params]
site_theme = "blue"
site_layout = "grid"
enable_jumbo = "true"
# truncate = "100"
about_logo = "npmrunpodcast-logo.png"
copyright_notice = "Copyright 2016 [Alan Blount](https://www.mattstrattion.io)"
itunes_subscribe = "http://itunes.apple.com/us/podcast/npmrunpodcast/id773888088?mt=2&uo=4&at=11lsCi"
android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
sticher_subscribe = "http://www.stitcher.com/podcast/npmrunpodcast-2/npmrunpodcast"
soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
mailchimp_subscribe = "//npmrunpodcast.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Aquire superpowers"
# media_prefix = "https://media.blubrry.com/npmrunpodcast/content.blubrry.com/npmrunpodcast/"
media_prefix = "https://runpodcast.github.io/website/"
  [params.feed]
    feed_copyright = "Copyright 2016 Alan Blount" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "Alan Blount" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Alan Blount"
    itunes_owner_email = "Alan.Blount@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://npmrunpodcast.com/img/npmrunpodcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    github = "npmrunpodcast"
    gitlab = "mattstratton"
    facebook = "npmrunpodcast"
    facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    twitter = "npmrunpodcast"
    twitter_domain = "npmrunpodcast.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "npmrunpodcast"
    pinterest = "nozzleio"
    instagram = "nozzleio"
    youtube = "npmrunpodcast"
    linkedin = "mattstratton"

  [params.authors]
    [params.authors.Alan]
      name	= "Alan Blount"
      thumbnail = "img/host/Alan.png"
      bio = "Alan Blount blah..."
      [params.authors.Alan.social]
        github = "mattstratton"
        facebook = "Alan.Blount"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.io"
        pinterest = "mattstratton"
        instagram = "instagram"
        youtube = "mattstratton"
    [params.authors.Aaron]
			name = "Aaron Johnson"
			thumbnail = "https://www.npmrunpodcast.com/img/Aaron.png"
			bio = ""
				[params.authors.Aaron.social]
					twitter = "trevorghess"
    [params.authors.Bridget]
      name = "Bridget Kromhout"
      thumbnail = "https://www.npmrunpodcast.com/img/Bridget.png"
      bio = ""
      [params.authors.Bridget.social]
        twitter = "bridgetkromhout"

    [params.links]
      [params.links.ado]
        name = "npm run podcast"
        url = "https://www.npmrunpodcast.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
