baseurl = "https://npmrunpodcast.com/"
languageCode = "en-us"
title = "npm run podcast"
theme = "super"
googleAnalytics = "UA-2011466-11"
disqusShortname = "zeroasterisk"
# themesdir = "../.."


[permalinks]
  # page = "/:filename/"
  about = "/:filename/"
  episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

# [[Menu.Main]]
#     name = "Contact"
#     identifier = "contact"
#     url = "contact"
#
# [[Menu.Main]]
#     name = "Guests"
#     identifier = "guests"
#     url = "guest"

[[Menu.Main]]
    name = "iTunes Subscribe"
    identifier = "itunes"
    url = "https://itunes.apple.com/us/podcast/npm-run-podcast/id1313639566"

# [[Menu.Main]]
#     name = "Resources"
#     identifier = "resources"
#     url = "#!"
#
# [[Menu.Main]]
#     name = "Books"
#     identifier = "books"
#     url = "books"
#     parent = "resources"
# [[Menu.Main]]
#     name = "Podcasts"
#     identifier = "podcasts"
#     url = "books"
#     parent = "resources"

[params]
site_theme = "blue"
site_layout = "grid"
enable_jumbo = "true"
# truncate = "100"
about_logo = "npmrunpodcast-logo.png"
copyright_notice = "Copyright 2017 [Alan Blount](https://zeroasterisk.com) [Aaron Johnson](https://github.com/TopShelfRobot)"
itunes_subscribe = "https://itunes.apple.com/us/podcast/npm-run-podcast/id1313639566"
android_subscribe = ""
google_play_subscribe = ""
sticher_subscribe = ""
soundcloud_subscribe = ""
pocketcasts_subscribe = ""
mailchimp_subscribe = ""
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Aquire superpowers"
# media_prefix = "https://media.blubrry.com/npmrunpodcast/content.blubrry.com/npmrunpodcast/"
media_prefix = "https://npmrunpodcast.com/"
  [params.feed]
    feed_copyright = "Copyright 2017 Alan Blount" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Informal tech talk for beginners, mids, and senior devs" #no markdown or HTML
    itunes_author = "Alan n Aaron" #no markdown or HTML
    itunes_summary = "Talk about web dev & devops: for beginners, mids, and seniors. Hang out with us and lets talk tech."
    itunes_owner_name = "Alan n Aaron"
    itunes_owner_email = "alan@zeroasterisk.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "http://npmrunpodcast.com/img/npmrunpodcast-logo.jpg" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    github = "npmrunpodcast"
    facebook = "npmrunpodcast"
    twitter = "npmrunpodcast"
    twitter_domain = "npmrunpodcast.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "npmrunpodcast"

  [params.authors]
    [params.authors.Alan]
      name  = "Alan Blount"
      thumbnail = "img/host/Alan.png"
      bio = "Alan Blount blah blah..."
      [params.authors.Alan.social]
        github = "zeroasterisk"
        facebook = "Alan.Blount"
        twitter = "zeroasterisk"
        linkedin = "zeroasterisk"
        homepage = "https://zeroasterisk.com"
        pinterest = "zeroasterisk"
        instagram = "zeroasterisk"
        youtube = "zeroasterisk"
    [params.authors.Aaron]
      name = "Aaron Johnson"
      thumbnail = "https://www.npmrunpodcast.com/img/Aaron.png"
      bio = "Arron Johnson blah blah..."
        [params.authors.Aaron.social]
          twitter = "ummm"

    [params.links]
      [params.links.ado]
        name = "npm run podcast"
        url = "https://npmrunpodcast.com"
