# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Super Powers"
license = "MIT"
licenselink = "https://en.wikipedia.org/wiki/MIT_License"
description = "minimal them, for a podcast site"
homepage = "https://github.com/runpodcast/"
tags = ["podcast", "bootstrap", "minimal", "responsive"]
features = ["disqus", "bootstrap", "responsive", "google analytics"]
min_version = 0.20

[author]
  name = "alan blount"
  homepage = "https://github.com/zeroasterisk"

# If porting an existing theme
[original]
  name = "Kishan B"
  homepage = "https://github.com/kishaningithub"
